name: Hope
version: '${project.version}'
main: me.opeten.hope.Hope
api-version: 1.19
commands:
  heal:
    description: Heals player to max health
    usage: /<command>
    aliases: [healing, healme, healmax, maxhealth]

  feed:
    description: Feeds player to max saturation
    usage: /<command>
    aliases: [feeding, feedme, feedmax, maxhunger]

  t:
    description: Sets time to day, kills all mobs except players and clears weather
    usage: /<command>
    aliases: [day, ready, go]

  farmtime:
    description: Spawns a specified farm animal
    usage: /<command> <animal> <amount>

  fly:
    description: enables player to fly
    usage: /<command>

